from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    ListFlowable,
    ListItem
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.pagesizes import letter

from reportlab.lib.enums import TA_CENTER

from reportlab.lib import colors

from reportlab.platypus.flowables import HRFlowable

from datetime import datetime

import uuid
import os

GENERATED_DIR = "generated_reports"

os.makedirs(
    GENERATED_DIR,
    exist_ok=True
)

def create_pdf(

    topic,
    report_content,
    font_name="Times-Roman",
    heading_size=30,
    subheading_size=20,
    paragraph_size=12

):

    file_id = str(uuid.uuid4())

    filename = f"{file_id}.pdf"

    file_path = os.path.join(
        GENERATED_DIR,
        filename
    )

    doc = SimpleDocTemplate(

        file_path,

        pagesize=letter,

        rightMargin=55,
        leftMargin=55,

        topMargin=55,
        bottomMargin=55

    )

    styles = getSampleStyleSheet()

    story = []

    # =========================
    # TITLE STYLE
    # =========================

    title_style = ParagraphStyle(

        "TitleStyle",

        parent=styles["Heading1"],

        fontName=font_name,

        fontSize=heading_size,

        leading=heading_size + 8,

        alignment=TA_CENTER,

        textColor=colors.HexColor("#0f172a"),

        spaceAfter=40

    )

    # =========================
    # HEADING STYLE
    # =========================

    heading_style = ParagraphStyle(

        "HeadingStyle",

        parent=styles["Heading2"],

        fontName=font_name,

        fontSize=subheading_size,

        leading=subheading_size + 10,

        textColor=colors.HexColor("#1d4ed8"),

        spaceBefore=20,

        spaceAfter=14

    )

    # =========================
    # BODY STYLE
    # =========================

    body_style = ParagraphStyle(

        "BodyStyle",

        parent=styles["BodyText"],

        fontName=font_name,

        fontSize=paragraph_size,

        leading=paragraph_size + 10,

        textColor=colors.black,

        spaceAfter=18

    )

    # =========================
    # COVER PAGE
    # =========================

    story.append(
        Spacer(1, 220)
    )

    story.append(

        Paragraph(
            f"{topic}<br/>Research Report",
            title_style
        )

    )

    story.append(
        Spacer(1, 50)
    )

    story.append(

        Paragraph(
            "Generated by ResearchAgent AI",
            body_style
        )

    )

    story.append(
        Spacer(1, 20)
    )

    story.append(

        Paragraph(
            datetime.now().strftime("%d %B %Y"),
            body_style
        )

    )

    story.append(PageBreak())

    # =========================
    # MAIN CONTENT
    # =========================

    lines = report_content.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        # =========================
        # HEADINGS
        # =========================

        if (
            len(line) < 60
            and not line.startswith("-")
            and not line.startswith("•")
            and ":" not in line
        ):

            story.append(

                Paragraph(
                    line,
                    heading_style
                )

            )

            story.append(

                HRFlowable(
                    width="100%",
                    thickness=1,
                    color=colors.HexColor("#cbd5e1")
                )

            )

            story.append(
                Spacer(1, 14)
            )

        # =========================
        # BULLET POINTS
        # =========================

        elif (
            line.startswith("-")
            or line.startswith("•")
        ):

            bullet = line.replace("-", "").replace("•", "").strip()

            story.append(

                Paragraph(
                    f"• {bullet}",
                    body_style
                )

            )

        # =========================
        # REFERENCES
        # =========================

        elif "References" in line:

            story.append(PageBreak())

            story.append(

                Paragraph(
                    line,
                    heading_style
                )

            )

        # =========================
        # NORMAL PARAGRAPHS
        # =========================

        else:

            story.append(

                Paragraph(
                    line,
                    body_style
                )

            )

    doc.build(story)

    return file_path

from docx import Document
from docx.shared import Pt

import uuid


def create_docx(

    topic,

    report_content,

    font_name,

    heading_size,

    subheading_size,

    paragraph_size

):

    document = Document()

    # =========================
    # TITLE
    # =========================

    title = document.add_heading(

        f"{topic} Research Report",

        level=0

    )

    title.runs[0].font.size = Pt(heading_size + 8)

    # =========================
    # CONTENT
    # =========================

    sections = report_content.split("##")

    for section in sections:

        if section.strip() == "":

            continue

        lines = section.strip().split("\n")

        heading = lines[0]

        content = "\n".join(lines[1:])

        # SUBHEADING

        subheading = document.add_heading(

            heading,

            level=1

        )

        subheading.runs[0].font.size = Pt(
            subheading_size
        )

        # PARAGRAPH

        para = document.add_paragraph(content)

        para.style.font.size = Pt(
            paragraph_size
        )

    # =========================
    # SAVE FILE
    # =========================

    filename = f"{uuid.uuid4()}.docx"

    filepath = f"generated_reports/{filename}"

    document.save(filepath)

    return filename